# Default values for postgresql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: postgres
  tag: "12.1"
  pullPolicy: IfNotPresent

service:
  ## PosgresSQL service type
  # type: ClusterIP
  type: NodePort
  port: 5432
  # clusterIP: None

ingress:
  enabled: false

# no specific resources
resources: {}
