# Default values for postgresql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: postgres
  tag: "12.1"
  pullPolicy: IfNotPresent

service:
  ## PosgresSQL service type
  # a ClusterIP uses internal cluster IP for the service
  # type: ClusterIP
  # a NodePort exposes the service on a static port on the node IP address
  type: NodePort
  port: 5432
  # clusterIP: None

ingress:
  enabled: true

# no specific resources
resources: {}
